### ISSUE TITLE
Missing offset property

### ISSUE THREAD

**Issue by tv104** [imagentleman/css-grid-overlay#1]
For designs which have a sidebar, it is common practice to apply the grid to the main content only.

![image](https://user-images.githubusercontent.com/1164786/57911650-99a31d00-7888-11e9-9bb3-3174f65f546f.png)

An offset property would allow users to specify where the grid really starts

**Comment by imagentleman** [comment]
A new version (6) was just published with this change. Should be available in a few minutes.
